name: dsec
path: datasets/DSEC
class_mode: 2class

sequence_length: 11
resolution_hw: [215, 320]
downsample_by_factor_2: false
min_bbox_diag: 20
min_bbox_height: 10
num_us: -1

eval:
  sampling: stream

flexfuse:
  dual_frequency:
    high_window_ratio: 0.5
    inference_seed: 42
